---
- name: "{{ 'Create' if (state is undefined or 'absent' not in state) else 'Terminate' }} EC2 instance ( Bastion )"
  ec2:
    assign_public_ip: yes
    count_tag:
      Name: "bastion"
    exact_count: "{{ 1 if (state is undefined or 'absent' not in state) else 0 }}"
    group: [
      "bastion"
    ]
    instance_type: "{{ ec2_type_bastion }}"
    image: "{{ ec2ami }}"
    instance_tags:
      Name: "bastion"
      clusterid: "{{ clusterid }}"
      ami: "{{ ec2ami }}"
      "kubernetes.io/cluster/{{ clusterid }}": "{{ clusterid }}"
    key_name: "{{ clusterid }}.{{ dns_domain }}"
    monitoring: no
    region: "{{ aws_region }}"
    termination_protection: no
    user_data: "{{ lookup('template', ( playbook_dir + '/roles/aws/templates/ec2_userdata.sh.j2') ) }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 25
        delete_on_termination: true
    vpc_subnet_id: "{{ item.subnet }}"
    wait: yes
  with_items:
    - name: "bastion"
      subnet: "{{ subnet_public.results.0.subnet.id if (state is undefined or 'absent' not in state) else '' }}"
      type: "{{ ec2_type_bastion }}"
  retries: 3
  delay: 3
  register: ec2bastion

- include_tasks: tag.yaml
  vars:
    - resource: "{{ item.tagged_instances[0].id }}"
    - tagss: "clusterid={{ clusterid }}, ami={{ ec2ami }}"
  with_items: "{{ ec2bastion.results }}"
  when:
    - ( state is undefined ) or ( 'absent' not in state )

- include_tasks: tag.yaml
  vars:
    - resource: "{{ item.tagged_instances[0].block_device_mapping['/dev/sda1'].volume_id }}"
    - tagss: "Name={{ item.tagged_instances[0].id }}-rootvol, clusterid={{ clusterid }}, "
  with_items: "{{ ec2bastion.results }}"
  when:
    - ( state is undefined ) or ( 'absent' not in state )

- name: "{{ 'Create' if (state is undefined or 'absent' not in state) else 'Terminate' }} EC2 instances ( Master )"
  ec2:
    assign_public_ip: no
    count_tag:
      Name: "{{ item.name }}"
    exact_count: "{{ 1 if (state is undefined or 'absent' not in state) else 0 }}"
    group: [
      "master",
      "node"
    ]
    instance_type: "{{ item.type }}"
    image: "{{ ec2ami }}"
    instance_tags:
      Name: "{{ item.name }}"
    key_name: "{{ clusterid }}.{{ dns_domain }}"
    monitoring: no
    region: "{{ aws_region }}"
    termination_protection: no
    user_data: "{{ lookup('template', ( playbook_dir + '/roles/aws/templates/ec2_userdata.sh.j2') ) }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 100
      - device_name: /dev/xvdb
        volume_type: gp2
        volume_size: 100
      - device_name: /dev/xvdc
        volume_type: gp2
        volume_size: 100
      - device_name: /dev/xvdd
        volume_type: gp2
        volume_size: 100
        delete_on_termination: true
    vpc_subnet_id: "{{ item.subnet }}"
    wait: yes
  with_items: "\
{%- set i = 1 -%}
{%- set j = 0 -%}
{%- for k in range(0, ( ec2_count_master if ec2_count_master is defined else 3 ) ) -%}
    {
'name': 'master{{ i }}',
'subnet': '{{ subnet_private.results[j].subnet.id if subnet_private is defined else '' }}',
'type': '{{ ec2_type_master }}'
    },
    {%- if i <= ( ec2_count_master if ec2_count_master is defined else 3 ) -%}
        {%- set i = i + 1 -%}
    {%- endif -%}
    {%- if subnet_private is defined -%}
      {%- if j < subnet_private.results | length - 1 -%}
          {%- set j = j + 1 -%}
      {%- else -%}
          {%- set j = 0 -%}
      {%- endif -%}
    {%- endif -%}
{%- endfor -%}
    "
  retries: 3
  delay: 3
  register: ec2master

- name: "Pause for 30 to allow for AWS to {{ 'instantiate' if (state is undefined or 'absent' not in state) else 'terminate' }}"
  pause:
    seconds: 30
  when: ec2master is changed

- include_tasks: tag.yaml
  vars:
    - resource: "{{ item.tagged_instances[0].id }}"
    - tagss: "clusterid={{ clusterid }}, ami={{ ec2ami }}, kubernetes.io/cluster/{{ clusterid }}={{ clusterid }}, host-type=master, sub-host-type=default"
  with_items: "{{ ec2master.results }}"
  when:
    - ( state is undefined ) or ( 'absent' not in state )

- include_tasks: tag.yaml
  vars:
    - resource: "{{ item.tagged_instances[0].block_device_mapping['/dev/sda1'].volume_id }}"
    - tagss: "Name={{ item.tagged_instances[0].id }}-rootvol, clusterid={{ clusterid }}, "
  with_items: "{{ ec2master.results }}"
  when:
    - ( state is undefined ) or ( 'absent' not in state )

- include_tasks: tag.yaml
  vars:
    - resource: "{{ item.tagged_instances[0].block_device_mapping['/dev/xvdb'].volume_id }}"
    - tagss: "Name={{ item.tagged_instances[0].id }}-xvdb, clusterid={{ clusterid }}, "
  with_items: "{{ ec2master.results }}"
  when:
    - ( state is undefined ) or ( 'absent' not in state )

- include_tasks: tag.yaml
  vars:
    - resource: "{{ item.tagged_instances[0].block_device_mapping['/dev/xvdc'].volume_id }}"
    - tagss: "Name={{ item.tagged_instances[0].id }}-xvdc, clusterid={{ clusterid }}, "
  with_items: "{{ ec2master.results }}"
  when:
    - ( state is undefined ) or ( 'absent' not in state )

- include_tasks: tag.yaml
  vars:
    - resource: "{{ item.tagged_instances[0].block_device_mapping['/dev/xvdd'].volume_id }}"
    - tagss: "Name={{ item.tagged_instances[0].id }}-xvdd, clusterid={{ clusterid }}, "
  with_items: "{{ ec2master.results }}"
  when:
    - ( state is undefined ) or ( 'absent' not in state )

- name: "{{ 'Create' if (state is undefined or 'absent' not in state) else 'Terminate' }} EC2 instances ( Infrastructure )"
  ec2:
    assign_public_ip: no
    count_tag:
      Name: "{{ item.name }}"
    exact_count: "{{ 1 if (state is undefined or 'absent' not in state) else 0 }}"
    group: [
      "infra",
      "node"
    ]
    instance_type: "{{ item.type }}"
    image: "{{ ec2ami }}"
    instance_tags:
      Name: "{{ item.name }}"
    key_name: "{{ clusterid }}.{{ dns_domain }}"
    monitoring: no
    region: "{{ aws_region }}"
    termination_protection: no
    user_data: "{{ lookup('template', ( playbook_dir + '/roles/aws/templates/ec2_userdata.sh.j2') ) }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 100
      - device_name: /dev/xvdb
        volume_type: gp2
        volume_size: 100
      - device_name: /dev/xvdc
        volume_type: gp2
        volume_size: 100
    vpc_subnet_id: "{{ item.subnet }}"
    wait: yes
  with_items: "\
{%- set i = 1 -%}
{%- set j = 0 -%}
{%- for k in range(0, ( ec2_count_infra if ec2_count_infra is defined else 3 ) ) -%}
    {
'name': 'infra{{ i }}',
'subnet': '{{ subnet_private.results[j].subnet.id if (state is undefined or 'absent' not in state) else '' }}',
'type': '{{ ec2_type_infra }}'
    },
    {%- if i <= ( ec2_count_infra if ec2_count_infra is defined else 3 ) -%}
        {%- set i = i + 1 -%}
    {%- endif -%}
    {%- if subnet_private is defined -%}
      {%- if j < subnet_private.results | length - 1 -%}
          {%- set j = j + 1 -%}
      {%- else -%}
          {%- set j = 0 -%}
      {%- endif -%}
    {%- endif -%}
{%- endfor -%}
    "
  retries: 3
  delay: 3
  register: ec2infra

- name: "Pause for 30 to allow for AWS to {{ 'instantiate' if (state is undefined or 'absent' not in state) else 'terminate' }}"
  pause:
    seconds: 30
  when: ec2infra is changed

- include_tasks: tag.yaml
  vars:
    - resource: "{{ item.tagged_instances[0].id }}"
    - tagss: "clusterid={{ clusterid }}, ami={{ ec2ami }}, kubernetes.io/cluster/{{ clusterid }}={{ clusterid }}, host-type=node, sub-host-type=infra"
  with_items: "{{ ec2infra.results }}"
  when:
    - ( state is undefined ) or ( 'absent' not in state )

- include_tasks: tag.yaml
  vars:
    - resource: "{{ item.tagged_instances[0].block_device_mapping['/dev/sda1'].volume_id }}"
    - tagss: "Name={{ item.tagged_instances[0].id }}-rootvol, clusterid={{ clusterid }}, "
  with_items: "{{ ec2infra.results }}"
  when:
    - ( state is undefined ) or ( 'absent' not in state )

- include_tasks: tag.yaml
  vars:
    - resource: "{{ item.tagged_instances[0].block_device_mapping['/dev/xvdb'].volume_id }}"
    - tagss: "Name={{ item.tagged_instances[0].id }}-xvdb, clusterid={{ clusterid }}, "
  with_items: "{{ ec2infra.results }}"
  when:
    - ( state is undefined ) or ( 'absent' not in state )

- include_tasks: tag.yaml
  vars:
    - resource: "{{ item.tagged_instances[0].block_device_mapping['/dev/xvdc'].volume_id }}"
    - tagss: "Name={{ item.tagged_instances[0].id }}-xvdc, clusterid={{ clusterid }}, "
  with_items: "{{ ec2infra.results }}"
  when:
    - ( state is undefined ) or ( 'absent' not in state )

- name: "{{ 'Create' if (state is undefined or 'absent' not in state) else 'Terminate' }} EC2 instances ( App )"
  ec2:
    assign_public_ip: no
    count_tag:
      Name: "{{ item.name }}"
    exact_count: "{{ 1 if (state is undefined or 'absent' not in state) else 0 }}"
    group: [
      "node"
    ]
    instance_type: "{{ item.type }}"
    image: "{{ ec2ami }}"
    instance_tags:
      Name: "{{ item.name }}"
    key_name: "{{ clusterid }}.{{ dns_domain }}"
    monitoring: no
    region: "{{ aws_region }}"
    termination_protection: no
    user_data: "{{ lookup('template', ( playbook_dir + '/roles/aws/templates/ec2_userdata.sh.j2') ) }}"
    volumes:
      - device_name: /dev/sda1
        volume_type: gp2
        volume_size: 100
      - device_name: /dev/xvdb
        volume_type: gp2
        volume_size: 100
      - device_name: /dev/xvdc
        volume_type: gp2
        volume_size: 100
    vpc_subnet_id: "{{ item.subnet }}"
    wait: yes
  with_items: "\
{%- set i = 1 -%}
{%- set j = 0 -%}
{%- for k in range(0, ( ec2_count_node if ec2_count_node is defined else 3 ) ) -%}
    {
'name': 'node{{ i }}',
'subnet': '{{ subnet_private.results[j].subnet.id if subnet_private is defined else '' }}',
'type': '{{ ec2_type_node }}'
    },
    {%- if i <= ( ec2_count_node if ec2_count_node is defined else 3 ) -%}
        {%- set i = i + 1 -%}
    {%- endif -%}
    {%- if subnet_private is defined -%}
      {%- if j < subnet_private.results | length - 1 -%}
          {%- set j = j + 1 -%}
      {%- else -%}
          {%- set j = 0 -%}
      {%- endif -%}
    {%- endif -%}
{%- endfor -%}
    "
  retries: 3
  delay: 3
  register: ec2node

- name: "Pause for 30 to allow for AWS to {{ 'instantiate' if (state is undefined or 'absent' not in state) else 'terminate' }}"
  pause:
    seconds: 30
  when: ec2node is changed

- include_tasks: tag.yaml
  vars:
    - resource: "{{ item.tagged_instances[0].id }}"
    - tagss: "clusterid={{ clusterid }}, ami={{ ec2ami }}, kubernetes.io/cluster/{{ clusterid }}={{ clusterid }}, host-type=node, sub-host-type=compute"
  with_items: "{{ ec2node.results }}"
  when:
    - ( state is undefined ) or ( 'absent' not in state )

- include_tasks: tag.yaml
  vars:
    - resource: "{{ item.tagged_instances[0].block_device_mapping['/dev/sda1'].volume_id }}"
    - tagss: "Name={{ item.tagged_instances[0].id }}-rootvol, clusterid={{ clusterid }}, "
  with_items: "{{ ec2node.results }}"
  when:
    - ( state is undefined ) or ( 'absent' not in state )

- include_tasks: tag.yaml
  vars:
    - resource: "{{ item.tagged_instances[0].block_device_mapping['/dev/xvdb'].volume_id }}"
    - tagss: "Name={{ item.tagged_instances[0].id }}-xvdb, clusterid={{ clusterid }}, "
  with_items: "{{ ec2node.results }}"
  when:
    - ( state is undefined ) or ( 'absent' not in state )

- include_tasks: tag.yaml
  vars:
    - resource: "{{ item.tagged_instances[0].block_device_mapping['/dev/xvdc'].volume_id }}"
    - tagss: "Name={{ item.tagged_instances[0].id }}-xvdc, clusterid={{ clusterid }}, "
  with_items: "{{ ec2node.results }}"
  when:
    - ( state is undefined ) or ( 'absent' not in state )
