---
- name: Register EC2 instances to internet-facing master ELB
  ec2_elb:
    instance_id: "{{ item.tagged_instances[0].id }}"
    ec2_elbs: "{{ elbextmaster.results[0].elb.name }}"
    region: "{{ aws_region }}"
    state: present
  with_items:
    - "{{ ec2master.results }}"
  register: test
  failed_when: "'InvalidInstanceID.NotFound' in test"

- name: Register EC2 instances to internal master ELB
  ec2_elb:
    instance_id: "{{ item.tagged_instances[0].id }}"
    ec2_elbs: "{{ elbintmaster.results[0].elb.name }}"
    region: "{{ aws_region }}"
    state: present
  with_items:
    - "{{ ec2master.results }}"
  register: test
  failed_when: "'InvalidInstanceID.NotFound' in test"

- name: Register EC2 instances to internet-facing infra ELB
  ec2_elb:
    instance_id: "{{ item.tagged_instances[0].id }}"
    ec2_elbs: "{{ elbextinfra.results[0].elb.name }}"
    region: "{{ aws_region }}"
    state: present
  with_items:
    - "{{ ec2infra.results }}"
  register: test
  failed_when: "'InvalidInstanceID.NotFound' in test"
