---
- name: "{{ 'Create' if (state is undefined or 'absent' not in state) else 'Terminate' }} VPC"
  ec2_vpc_net:
    cidr_block: "{{ vpc_cidr }}"
    dhcp_opts_id: "{{ vpcdhcpopts.dhcp_options_id if (state is undefined or 'absent' not in state) else '' }}"
    name: "{{ clusterid }}"
    region: "{{ aws_region }}"
    state: "{{ state | default('present') }}"
  retries: 3
  delay: 5
  register: vpc
