---
- name: "Create VPC DHCP Options"
  ec2_vpc_dhcp_options:
    domain_name: "{{ 'ec2.internal' if (aws_region == 'us-east-1') else aws_region + '.compute.internal' }}"
    region: "{{ aws_region }}"
    dns_servers:
      - AmazonProvidedDNS
    inherit_existing: False
  retries: 3
  delay: 3
  register: vpcdhcpopts
