---
- hosts: localhost
  user: root
  become: false
  ignore_errors: yes
  vars_files:
    - vars/main.yaml
  roles:
    - instance-groups

- hosts: cns
  user: root
  become: false
  ignore_errors: yes
  vars_files:
    - vars/main.yaml
  roles:
    - rhsm-unregister

- hosts: localhost
  user: root
  become: false
  ignore_errors: yes
  vars_files:
    - vars/main.yaml
  tasks:
    - name: Delete cns VMs
      vmware_guest:
        hostname: "{{ openshift_cloudprovider_vsphere_host }}"
        username: "{{ openshift_cloudprovider_vsphere_username }}"
        password: "{{ openshift_cloudprovider_vsphere_password }}"
        datacenter: "{{ openshift_cloudprovider_vsphere_datacenter }}"
        folder: "/{{ openshift_cloudprovider_vsphere_folder }}"
        name: "{{ item.value.guestname }}"
        state: absent
        force: true
      with_dict: "{{host_inventory}}"
      when: "'cns' in item.value.guestname"
