---
- include: /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/{{ openshift_vers | default('v3_9') }}/upgrade.yml
  vars:
    debug_level: 2
    openshift_debug_level: "{{ debug_level }}"
    openshift_master_cluster_method: native
    openshift_node_debug_level: "{{ node_debug_level | default(debug_level, true) }}"
    openshift_master_debug_level: "{{ master_debug_level | default(debug_level, true) }}"
    openshift_master_access_token_max_seconds: 2419200
    openshift_master_api_port: "{{ console_port }}"
    openshift_master_console_port: "{{ console_port }}"
    osm_cluster_network_cidr: 172.16.0.0/16
    openshift_cloudprovider_kind: vsphere
    load_balancer_hostname:
    deployment_type:
    openshift_master_cluster_hostname: "{{ load_balancer_hostname }}"
    openshift_master_cluster_public_hostname: "{{ load_balancer_hostname }}"
    osm_default_node_selector: "role=app"
