---
- name: Assign app memory for container_storage
  set_fact:
    app_memory: 32768
  when: "'cns' in container_storage"

- name: Assign app memory for container_storage
  set_fact:
    app_memory: 8192
  when: "'cns' not in container_storage"

- name: Create additional production VMs on vCenter
  vmware_guest:
    hostname: "{{ openshift_cloudprovider_vsphere_host }}"
    username: "{{ openshift_cloudprovider_vsphere_username }}"
    password: "{{ openshift_cloudprovider_vsphere_password }}"
    validate_certs: False
    name: "{{ item.value.guestname }}"
    cluster: "{{ openshift_cloudprovider_vsphere_cluster}}"
    datacenter: "{{ openshift_cloudprovider_vsphere_datacenter }}"
    resource_pool: "{{ openshift_cloudprovider_vsphere_resource_pool }}"
    template: "{{openshift_cloudprovider_vsphere_template}}"
    state: poweredon
    wait_for_ip_address: True
    folder: "{{ openshift_cloudprovider_vsphere_datacenter }}/vm/{{ openshift_cloudprovider_vsphere_folder }}"
    annotation: "{{ item.value.tag }}"
    hardware:
      memory_mb: "{{ app_memory }}"
    networks:
    - name: "{{ openshift_cloudprovider_vsphere_vm_network }}"
      ip: "{{ item.value.ip4addr }}"
      netmask: "{{ openshift_cloudprovider_vsphere_vm_netmask }}"
      gateway: "{{ openshift_cloudprovider_vsphere_vm_gateway }}"
    customization:
      domain: "{{default_subdomain}}"
      dns_servers:
      - "{{ openshift_cloudprovider_vsphere_vm_dns }}"
      dns_suffix: "{{default_subdomain}}"
      hostname: "{{ item.value.guestname}}"
  with_dict: "{{host_inventory}}"
  when: "'master' in item.value.guestname or 'app' in item.value.guestname or 'infra' in item.value.guestname"

- name: Add additional production VMs to inventory
  add_host: hostname="{{ item.value.guestname }}" ansible_ssh_host="{{ item.value.ip4addr }}" groups="{{ item.value.tag }}, production_group, new_nodes"
  with_dict: "{{host_inventory}}"
  when: "'master' in item.value.guestname or 'app' in item.value.guestname or 'infra' in item.value.guestname"
