---
# repos from https://docs.openshift.com/container-platform/3.9/install_config/install/host_preparation.html#host-registration
openshift_required_repos:
  - 'rhel-7-server-rpms'
  - 'rhel-7-server-extras-rpms'
  - 'rhel-7-server-ose-3.9-rpms'
  - 'rhel-7-fast-datapath-rpms'
  - 'rhel-7-server-ansible-2.4-rpms'
